# Generated by Django 5.0.2 on 2026-02-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='telegram', max_length=20),
        ),
    ]
