# Generated by Django 5.0.2 on 2026-02-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('faq', 'FAQ'), ('file', 'File'), ('text', 'Text Content')], default='faq', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Question or Topic', max_length=255)),
                ('content', models.TextField(blank=True, help_text='Answer or Content')),
                ('file', models.FileField(blank=True, null=True, upload_to='knowledge/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('webhook_status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
