# Generated by Django 5.0.2 on 2026-02-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='whatsapp_access_token',
            field=models.TextField(blank=True, help_text='WhatsApp Cloud API access token', null=True),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, help_text='WhatsApp Phone Number ID from Meta', max_length=100, null=True),
        ),
    ]
